version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker: # executor type
      - image: cimg/python:3.10 
    steps:
      - checkout
      - run:
          name: install
          command: pip install .
      - run:
          name: test
          command: python -m pytest

workflows:
  main:
    jobs:
      - build_and_test
