version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker: # executor type
      - image: cimg/python:3.10 
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  main:
    jobs:
      - build_and_test
